### ISSUE TITLE
Authenticating from Admin section not working

### ISSUE THREAD

**Issue by milikicn** [Otto42/simple-twitter-connect#1]
I have installed the plugin and activated 'Simple Twitter Connect - Base'. I have also activated 'STC - Publish'. And now in the STC Settings page when I want to authenticate my account for publishing and click on the blue 'Sing in with Twitter' button, it redirects me to the Twitter page with error:

![screenshot 2015-04-27 23 07 44](https://cloud.githubusercontent.com/assets/26282/7357923/48424dcc-ed32-11e4-8183-9eed8db93369.png)

The problem is that the oauth token is not contained in the URL, see the example: https://twitter.com/oauth/authorize?oauth_token=

**Comment by Otto42** [comment]
STC has not been actively developed for years, and I have no real plans to start working on it again. This repo is mainly here as an archive, you're free to do whatever you like with it.
